# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Cristian G Guerrero: personal website"
description: > # this means to ignore newlines until "baseurl:"
  I'm a passionate Engineer and a Free Software lover. Never stop scripting!!!
repository: https://github.com/guyikcgg/guyikcgg.github.io/
# baseurl: # the subpath of your site, e.g. /blog
url: https://guyikcgg.github.io/  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Cristian G Guerrero
email: guyikcgg@gmail.com

navigation:
  - text: About me
    url: "#about-me"
  - text: About this site
    url: "#about-this-site"
  - text: Projects
    url: "#projects"
    title: "projects"
  - text: Contact me
    url: "#contact-me"

project_sections:
  - sec_name: "Gaming projects"
    id: recent-projects
    projects:
      - name: "D-pueblo"
        description: "Board game to talk about the depopulation of rural areas. AWARD: Best board game @ Jamtoday Granada 2020."
        image: "projects/d-pueblo/d-pueblo.png"
        date: 2020
        links:
          - text: "game instructions (Spanish)"
            url: https://docs.google.com/document/d/1htpeIOqn4h3VaautKxDRAaAUZ3ErzUL0D7glU3V0G5M
          - text: "making of and unboxing [youtube]"
            url: https://www.youtube.com/watch?v=laR1zVCKP9s
      - name: "True VS Fake"
        description: "Videogame to talk about the spread of fake news. Developed on Unity. AWARD: Best videogame design @ Jamtoday Granada 2018."
        date: 2018
        image: projects/true_vs_fake/screenshot_001.jpg
        github: https://github.com/guyikcgg/Jamtoday-2018
        links:
          - text: "making of [youtube]"
            url: https://youtu.be/zbgDVoRsS_o

  - sec_name: "Academic projects"
    id: academic-projects
    projects:
      - name: Seguridad de los Datos en Sistemas Empotrados
        description: "Master thesis: Cybersecurity in Embedded Systems (Spanish)."
        date: 2018
        github: https://github.com/guyikcgg/Trabajo-Fin-de-Master
        links:
          - text: slides
            url: projects/tfm/index.html
          - text: "report [pdf]"
            url: https://github.com/guyikcgg/Trabajo-Fin-de-Master/raw/master/memoria/TFM-Cristian-Gonzalez-Guerrero.pdf
      - name: Visión Interior (Semir Zeki)
        description: Presentation connecting the perception of art with human's vision system (Spanish).
        image: projects/vision_interior/img/paolo_uccello_031-detail-sq.jpg
        links:
          - text: slides
            url: projects/vision_interior/index.html
      - name: DHCP Relay Agent
        description: DHCP Relay Agent developed during college
        date: 2014
        image: projects/dhcp-relay-agent/dhcp-relay-agent.png
        links:
          - text: report [pdf]
            url: https://sourceforge.net/p/dhcprelayagent/code/HEAD/tree/tags/v1.00/Rapport.pdf?format=raw
          - text: source code
            url: https://sourceforge.net/p/dhcprelayagent/code/HEAD/tree/tags/v1.00/

  - sec_name: "Other projects"
    id: other-projects
    projects:
      - name: ECOpilot
        image: https://adescobar.github.io/ECOpilot/img/logo.png
        description: "A smart gas-sensing system to monitor vehicle pollution. AWARD: Finalist project @ Valeo Innovation Challenge 2017."
        date: 2017
        links:
          - text: website
            url: https://adescobar.github.io/ECOpilot/
          - text: poster
            url: projects/ecopilot/ecopilot-poster.jpg
          - text: souvenir [youtube]
            url: https://www.youtube.com/watch?v=LXZLXaLkBHU
      - name: Me Tropecé con la Alcachofa
        image: https://guyikcgg.gitlab.io/me-tropece-con-la-alcachofa/assets/images/arroz-con-leche-01.jpg
        description: "Recetario para consulta propia."
        date: 2017
        links:
          - text: website
            url: https://guyikcgg.gitlab.io/me-tropece-con-la-alcachofa/

  - sec_name: "Graphic design"
    id: graphic-design
    projects:
      - name: "[SCOPE] Dossier for a robotic workshop"
        is_graphic: true
        image: projects/graphic_design/dossier_digital.jpg
        description: "Dossier for marketing a robotic workshop."
        links:
          - text: "dossier [pdf]"
            url: projects/graphic_design/dossier_digital.pdf

social:
  - service: github
    username: guyikcgg
    link: https://github.com/guyikcgg
  - service: stackoverflow
    username: guyik
    link: https://stackoverflow.com/users/3761766/guyik
  - service: linkedin
    username: CristianGGuerrero
    link: https://www.linkedin.com/in/cristiangguerrero/
  - service: telegram
    username: CristianCGG
    link: https://t.me/CristianCGG
    # TODO add StackExchange and DEV

# Plugins
plugins:
  - jekyll-seo-tag
