# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Cristian G Guerrero: personal website"
description: > # this means to ignore newlines until "baseurl:"
  Telecommunications engineer and free software developper
repository: https://github.com/guyikcgg/guyikcgg.github.io/
# baseurl: # the subpath of your site, e.g. /blog
url: https://guyikcgg.github.io/  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Cristian G Guerrero
email: guyikcgg@gmail.com

navigation:
  - text: About me
    url: "#about-me"
  - text: About this site
    url: "#about-this-site"
  - text: Projects
    url: "#projects"
    title: "projects"
  - text: Contact me
    url: "#contact-me"

project_sections:
  - sec_name: "Recent projects"
    id: recent-projects
    projects:
      - name: "True VS Fake"
        description: "Videogame to talk about the spread of fake news (made with Unity engine). AWARD: Best design at Jamtoday Granada 2018."
        image: projects/true_vs_fake/screenshot_001.jpg
        github: https://github.com/guyikcgg/Jamtoday-2018
        links:
          - text: "making of [youtube]"
            url: https://youtu.be/zbgDVoRsS_o
      - name: Seguridad de los Datos en Sistemas Empotrados
        description: "Master thesis: Cybersecurity in Embedded Systems (Spanish)."
        date: 2018
        github: https://github.com/guyikcgg/Trabajo-Fin-de-Master
        links:
          - text: slides
            url: projects/tfm/index.html
          - text: "report [pdf]"
            url: https://github.com/guyikcgg/Trabajo-Fin-de-Master/raw/master/memoria/TFM-Cristian-Gonzalez-Guerrero.pdf
      - name: Visión Interior (Semir Zeki)
        description: Presentation connecting the perception of art with human's vision system (spanish).
        image: projects/vision_interior/img/paolo_uccello_031-detail-sq.jpg
        links:
          - text: slides
            url: projects/vision_interior/index.html
  - sec_name: "Other projects"
    id: other-projects
    projects:
      - name: ECOpilot
        image: https://adescobar.github.io/ECOpilot/img/logo.png
        description: "A small gas-sensing system to monitor vehicle pollution. AWARD: Finalist in Valeo Innovation Challenge 2017"
        links:
          - text: website
            url: http://myecopilot.com
          - text: poster
            url: projects/ecopilot/ecopilot-poster.jpg

social:
  - service: github
    username: guyikcgg
    link: https://github.com/guyikcgg
  - service: twitter
    username: guyikcgg
    link: https://twitter.com/guyikcgg
  - service: linkedin
    username: CristianGGuerrero
    link: https://www.linkedin.com/in/cristiangguerrero/
  - service: telegram
    username: CristianCGG
    link: https://t.me/CristianCGG
    # TODO add StackExchange and Wikipedia

# Plugins
plugins:
  - jekyll-seo-tag
